### ISSUE TITLE
Selection of tract is not specific due to "leaking" voxels

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/atlas-rat#1]
When running scatlas_extract_metric.m, the tract definition is incorrect because the algorithm to deal with partial volume (i.e. tract value is NOT specific to tract) is not robust. See figure below:

![screen shot 2018-11-08 at 14 14 37](https://user-images.githubusercontent.com/2482071/48221654-a5090f00-e360-11e8-9422-062cefb684de.png)

A solution would be to fix the interpolation in order to have a proper tract volume to start from.

**Comment by jcohenadad** [comment]
One possible cause of the problem is the inaccurate manually-drawn tract, which includes spurious values between tracts, see below:
![screen shot 2018-11-08 at 14 27 07](https://user-images.githubusercontent.com/2482071/48222389-80ae3200-e362-11e8-988d-81f552652da3.png)

This needs to be fixed before moving forward

**Comment by jcohenadad** [comment]
A possible approach is to apply a median filter on the existing tract images. Implemented in bde543909a3a725ee1d2152e14202a0ea5e3f82c

**Comment by HarrisNami** [comment]
Works for every level but S2, S3, S4 (images below). 

![screen shot 2018-11-08 at 6 06 50 pm](https://user-images.githubusercontent.com/29234406/48232912-37b9a600-e381-11e8-818d-4080d562ad54.png)
![screen shot 2018-11-08 at 6 07 03 pm](https://user-images.githubusercontent.com/29234406/48232913-37b9a600-e381-11e8-8e3f-e58353ac0750.png)
![screen shot 2018-11-08 at 6 07 13 pm](https://user-images.githubusercontent.com/29234406/48232914-38523c80-e381-11e8-8e97-0b736b6ec1c3.png)

**Comment by jcohenadad** [comment]
I would just fix the tract image on those levels

**Comment by HarrisNami** [comment]
Just to be sure, do you mean to redo the initial digitalized paxinos for these levels (i.e. the image below)?
![screen shot 2018-11-08 at 6 32 35 pm](https://user-images.githubusercontent.com/29234406/48233840-d0055a00-e384-11e8-9176-302d82960095.png)

**Comment by jcohenadad** [comment]
I meant just edit the pixels on this image (tge black and white you posted above) that are problematic (remove the obvious spurious pix, the median filter will do the rest)

**Comment by HarrisNami** [comment]
So after having removed the pixels and testing again the outcome was the same. What I realize is that the issue occurs due to the resizing of the tracts image which occurs after the fmedian is applied. Maybe it should be applied again after image resizing?

Initial Image
![screen shot 2018-11-09 at 3 34 12 pm](https://user-images.githubusercontent.com/29234406/48287150-e3bcc900-e435-11e8-8cec-0f605b08e849.png)

Resized Image 
![screen shot 2018-11-09 at 3 34 27 pm](https://user-images.githubusercontent.com/29234406/48287164-ee775e00-e435-11e8-9696-472bcb4a0d46.png)

**Comment by jcohenadad** [comment]
> Maybe it should be applied again after image resizing?

no, resizing should be done with NN interpolation (not linear)
